apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
spec:
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: corentinth/it-tools:2024.10.22-7ca5933
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
spec:
  type: LoadBalancer
  selector:
    app: it-tools
  ports:
  - port: 80
    targetPort: 80
