apiVersion: v1
kind: Service
metadata:
  name: pgsql-loadbalancer
spec:
  selector:
    cnpg.io/cluster: pgsql-cluster
    cnpg.io/instanceRole: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
  loadBalancerIP: 192.168.0.25
