apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-ingress-cert
  namespace: linkding
spec:
  dnsNames:
    - linkding.1earn.ing
    - linkding.int.1earn.ing
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-clusterissuer
  secretName: linkding-ingress-cert-secret
