apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  template:
    spec:
      containers:
        - name: linkding
          env:
            - name: LD_ENABLE_AUTH_PROXY
              value: "True"
            - name: LD_AUTH_PROXY_USERNAME_HEADER
              value: HTTP_X_AUTHENTIK_USERNAME
            - name: LD_AUTH_PROXY_LOGOUT_URL
              value: https://auth.1earn.ing/outpost.goauthentik.io/sign_out
