apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding
  namespace: linkding
spec:
  entryPoints:
    - websecure
    - ext-websecure
  routes:
    - kind: Rule
      match: Host(`linkding.1earn.ing`) || Host(`linkding.int.1earn.ing`)
      priority: 10
      services:
        - name: linkding
          port: 9090
      middlewares:
        - name: authentik
          namespace: authentik

    # Redirects for Authentik Outpost
    - kind: Rule
      match: Host(`linkding.1earn.ing`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 15
      services:
      - kind: Service
        namespace: authentik
        name: ak-outpost-authentik-embedded-outpost
        port: 9000

    # Expose the API since it requires a valid token.
    - kind: Rule
      match: Host(`linkding.1earn.ing`) && PathPrefix(`/api/bookmarks/`)
      services:
        - name: linkding
          port: 9090
  tls:
    secretName: linkding-ingress-cert-secret
