apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding
  namespace: linkding
spec:
  entryPoints:
    - websecure
    - ext-websecure
  routes:
    - kind: Rule
      match: Host(`linkding.1earn.ing`) || Host(`linkding.int.1earn.ing`)
      services:
        - name: linkding
          port: 9090
  tls:
    secretName: linkding-ingress-cert-secret
