apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
spec:
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: docker.io/sharevb/it-tools@sha256:06da57c43b137afebfa4d4f6d396b4a89b656075428ae8386da213f4b314e13d
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
spec:
  type: ClusterIP
  selector:
    app: it-tools
  ports:
  - port: 80
    targetPort: http
