apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - longhorn-cnpg-storageclass.yaml
  - pg-cluster.yaml
  # Barman Cloud plug-in for backup
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.5.0/manifest.yaml
  - pgsql-backup_sealedsecrets.yaml
  - pgsql-backup_objectstore.yaml
  - pgsql_backup.yaml
  - pgsql_scheduledbackup.yaml
