apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgsql-cluster
  labels:
    app.kubernetes.io/component: database
spec:
  instances: 3

  storage:
    storageClass: longhorn-cnpg
    size: 12Gi

  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
