apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pgsql-cluster-backup
spec:
  cluster:
    name: pgsql-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
