apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: metallb_argocd.yaml
  - path: kube-prometheus-stack_argocd.yaml
  - path: cert-manager_argocd.yaml
  - path: cert-manager/letsencrypt-issuer.yaml
  - path: longhorn-argocd.yaml
  - patch: |
      - op: replace
        path: /spec/sources/1
        value: {
          repoURL: http://truenas.local:30008/tawdball/homelab.git,
          path: infra/homelab/pgsql,
          targetRevision: HEAD
        }
    target:
      kind: Application
      name: postgresql
      namespace: argocd
  - patch: |
      - op: replace
        path: /spec/sources/1
        value: {
          repoURL: http://truenas.local:30008/tawdball/homelab.git,
          path: infra/homelab/authentik,
          targetRevision: HEAD
        }
    target:
      kind: Application
      name: authentik
      namespace: argocd
