apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: metallb_argocd.yaml
  - path: kube-prometheus-stack_argocd.yaml
  - path: cert-manager_argocd.yaml
  - path: cert-manager/letsencrypt-issuer.yaml
  - path: longhorn-argocd.yaml
  - patch: |
      - op: replace
        path: /spec/sources/1
        value: {
          path: infra/homelab/pgsql,
          targetRevision: main
        }
    target:
      kind: Application
      name: postgresql
      namespace: argocd
  - patch: |
      - op: replace
        path: /spec/sources/1
        value: {
          path: infra/homelab/authentik,
          targetRevision: main
        }
    target:
      kind: Application
      name: authentik
      namespace: argocd
  - path: traefik_argocd.yaml
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: http://truenas:30008/tawdball/homelab.git
    target:
      kind: Application
      namespace: argocd
      labelSelector: isHelm=false
  - patch: |-
      - op: replace
        path: /spec/sources/1/repoURL
        value: http://truenas:30008/tawdball/homelab.git
    target:
      kind: Application
      namespace: argocd
      labelSelector: isHelm=partial
