apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - argocd/argocd_ingress.yaml
  - cert-manager
patches:
  - path: metallb_argocd.yaml
  - path: kube-prometheus-stack_argocd.yaml
  - path: cert-manager_argocd.yaml
  - path: longhorn-argocd.yaml
  - patch: |
      - op: replace
        path: /spec/sources/1
        value: {
          path: infra/homelab/pgsql,
          targetRevision: main
        }
    target:
      kind: Application
      name: postgresql
      namespace: argocd
  # Authentik patches
  - patch: |
      - op: replace
        path: /spec/sources/0/targetRevision
        value: 2025.6.3
      - op: replace
        path: /spec/sources/1
        value: {
          path: infra/homelab/authentik,
          targetRevision: main
        }
    target:
      kind: Application
      name: authentik
      namespace: argocd
  # Traefik patches
  - path: traefik_argocd.yaml
  - patch: |-
      - op: add
        path: /spec/source/helm/valuesObject/ports/ext-websecure/forwardedHeaders/trustedIPs/-
        value: 10.244.0.0/16
      - op: add
        path: /spec/source/helm/valuesObject/ports/ext-websecure/forwardedHeaders/trustedIPs/-
        value: 10.96.0.0/12
      - op: add
        path: /spec/source/helm/valuesObject/ports/ext-websecure/forwardedHeaders/trustedIPs/-
        value: 192.168.0.0/22
      - op: add
        path: /spec/source/helm/valuesObject/ports/websecure/forwardedHeaders/trustedIPs/-
        value: 10.244.0.0/16
      - op: add
        path: /spec/source/helm/valuesObject/ports/websecure/forwardedHeaders/trustedIPs/-
        value: 10.96.0.0/12
      - op: add
        path: /spec/source/helm/valuesObject/ports/websecure/forwardedHeaders/trustedIPs/-
        value: 192.168.0.0/22
    target:
      kind: Application
      namespace: argocd
      name: traefik
  # General ArgoCD application patches
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://truenas.int.1earn.ing:30008/tawdball/homelab.git
    target:
      kind: Application
      namespace: argocd
      labelSelector: isHelm=false
  - patch: |-
      - op: replace
        path: /spec/sources/1/repoURL
        value: https://truenas.int.1earn.ing:30008/tawdball/homelab.git
    target:
      kind: Application
      namespace: argocd
      labelSelector: isHelm=partial
