apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    targetRevision: 36.0.0
    helm:
      valuesObject:
        service:
          type: LoadBalancer
          spec:
            loadBalancerIP: 192.168.0.20
          logs:
            access:
              enabled: true
