configs:
  params:
    # Turn off secure to use our own Ingress
    server.insecure: true
    dexserver.disable.tls: true
    server.dex.server.plaintext: true
  # Use secret values found in the "authentik-dex-secrets" secret. See:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
  cm:
    url: https://argocd.1earn.ing
    dex.config: |
      connectors:
      - config:
          issuer: https://auth.1earn.ing/application/o/argo-cd/
          clientID: $authentik-dex-secrets:clientID
          clientSecret: $authentik-dex-secrets:clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
  rbac:
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly
