---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBptFTQJzuU7yrgp3BwUezYH27HznrkG8NDrlnn5YM7QkDPDiu3Jr7p9/DvOyDwbjBI8iFvwU0RXAcRYzSH4Q7RNSTEZRRs0bBnN5h2o7XFfuBUaiboguFmVLhX4CQJTv6ClcZOXIEg322QdCsYR/lBeX/DH3ZE1IuV8P0oAzZsMCIpW+3ww4mhdCQqgyQCoa3CdW49e4AXd8PDpUU9URsuY8dpGdZMPzfCLI8IGCtfktVNDiBx8UkaAOYcnAe9/YxL5CYy0+V1YzERcBfEELW4R5Tkukex1IAOehkw2cJgJlJEu70luhpKiBcB+RuSdgMHm0ERaPhJp7WAotElVaQiLK8egksGRdMIRAl+Rc+ZwELD0Vyn8CyOCYDfmXWAShVL7JJrcIx/Nb+SiGLy+p+G9yjVcJg7QIwbKGC/4x73sol1nDcxLVL4WjBQ19flC3+4NxodG4SKosmu154t4igAwcByj0w0oTb0994Dfg6R64suxWAjlR16fqkkVEBqU1WPVDS+ZHW8uyoONQHSqU1bIdjMGm5IrGSAfYH/nppijkyCPat9SmC9YUwSmiEOnUCpdKMFllXHeaWxw7iPf2D0AOR9qwOXKCMOfcHh2NIebByj+9b/jdpEl+O/sbbCE1143qEZWwIO8ixIq8QdoEdDjdvpC1tUkxllOitRzHEz3UNfvgNbFu6dYi9E/IidhTCCLL0HomG7inVt30dq9d12okjl0RmWqOWbTyq0dRoBQm2oPHJhrM0t
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
