apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.1
    helm:
      valuesObject:
        defaultSettings:
          orphanAutoDeletion: false
          autoDeletePodWhenVolumeDetachedUnexpectedly: true
          nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
          nodeDrainPolicy: always-allow
        preUpgradeChecker:
          jobEnabled: false
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
