apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    isHelm: "true"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.2.*
    helm:
      releaseName: traefik
      valuesObject:
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          ext-websecure:
            port: 7443
            exposedPort: 7443
            expose:
              default: true
            forwardedHeaders:
              trustedIPs:
              - 173.245.48.0/20
              - 103.21.244.0/22
              - 103.22.200.0/22
              - 103.31.4.0/22
              - 141.101.64.0/18
              - 108.162.192.0/18
              - 190.93.240.0/20
              - 188.114.96.0/20
              - 197.234.240.0/22
              - 198.41.128.0/17
              - 162.158.0.0/15
              - 104.16.0.0/13
              - 104.24.0.0/14
              - 172.64.0.0/13
              - 131.0.72.0/22
          websecure:
            forwardedHeaders:
              trustedIPs: []
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
