apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    isHelm: "true"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.0.*
    helm:
      releaseName: traefik
      valuesObject:
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          ext-web:
            port: 7080
            exposedPort: 7080
            expose:
              default: true
          ext-websecure:
            port: 7443
            exposedPort: 7443
            expose:
              default: true
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
