apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 34.5.0
    helm:
      releaseName: traefik
      valuesObject:
        service:
          type: LoadBalancer
          spec:
            loadBalancerIP: 192.168.0.20
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
