apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 34.5.0
    helm:
      releaseName: traefik
      values: |
        service:
          type: LoadBalancer
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          web:
            redirectTo: websecure
          websecure:
            tls:
              enabled: true
        dashboard:
          enabled: true
  destination:
    server: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
