---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    SECRET_KEY: AgCZia0nQJm5huszd1AIzJn+P5ekPaDJdEVnaA7IDp3c6ScqbVkxZsEmGFeyNVXGjtWirY2zz6ApsRBdajP2KCj47ouo2XIrTU0KvzgOKC4LpI0ZYo6qXvQM8Xti4pSr44K9H7iE9Z3/Iws8Rw50Gxw88DXBiGhd0tmLbLnbbL8som5ty6KsR1sdti/Pa/ho3aPSHW1K7T0nLA2FSKDJYG8ZGJNJsT2Qh/V7D1RBnfqbgM4Vjp8oHpnKRUDnv20K01M11cFUWDN3dGGSSH4RvAXyyW9MtAICQci6VRmR20DXhFtoQvGC1rie3IsnWVo6Q59YuwWU1vWwbO8ZGk9pCLA7fJ5PYtCNzVaO8NryMDmOxSdHIZqeOsSUYASO8LxVsfRkZ2ACeoWNhFcnA+xhoAA2Uet3vynOwnXFeJsdhv6GwRROTQanqmuc6JA3nKvG7XI6Uylgyuk4xlPRYlWtdr10xm+WktqpIfaRwGYKMGv5JDyfnf77YFFdS6/nATW9JNY439nrhUZQGGcOgzZK92qiVY5+N+EjwKbxm3vFA1yKhHsvm0Qcy92q897Fqcp2Snft/X+pKVm44pFdG8PSAVbqq/PnUztrG9yHJay5cqmluL0pRm+CsZdw/S9WvvLzOVcEUFohMel3wVIzYl0exW8ILBBisb1mbFXXD7l6qrPxfSFxQo/kbWKjZfO/HIzlkF5s+ZnrO7iYO9+n6BsrYtpIjltruLraDhVjC3m5o46XPgFWxrv5xZfEjkAykXxrzD0dLQ==
    redis_pw: AgBZ0E2aPVHB6g0aT4FY23dRMG44OJhV0ln7NADtNY1qWptHKvYMxGTqnKOxQ5214a+HXiFqtqEiF1oPfWHwLJ+WJbAYhsbkP5zn8t0Y8nw1zVt36p35FdJnVzYD9WYlmb8BEfIyAeayR8qvw+qEZA5aOK547TIpzYNdfe39qNiIUCsH4IoH+RS4MlTFWny+913xqsvWz095OlHITG80Paxeb/XjJzaeWveNEDlC3YlHY8jQT9J5L2uz8TZalyydXx1qi8/R4nQXq5a2qDSTUCw0FRm1Vk1oEBvpyO/2CZ3e08h3YEpexl5Rp+Mcx0aMufPiJ4t0MMefKl4WXcJuzsFLT3hdRHkxni+djXk5ddHX/sTcu3/zZtv/Ez7pyjcTZ7NGu+RuBQSyR/lD8rYRLpFeBSoLj9HDYJyUDQwxrHZv7k6a3INA8oXVpiNgxsg3x4d97J4b3x3BJ756eA0EYht1U5iW4s4zSzsGkwoAReMj+/A481bqFs1XqObPlI/ie1MBMviTP/lXmsbpx1kmEQqZlAMwR2A5McCjvke7vyJIpDEBIPkjyeYOkGMvz3TRUniAB0jXV20A9y02ximTCxGaApsHnH9l0tZtmnniYbCCWFd750xRyj2Na6GTUQ3Xkbq5NOIL7DmhqrhYQ1k9qioSXDzEAjxRYWDmqhdY8rRPoRML8mmPRYXmvM8/vd8ExhD0Q/Rth7FACnnX+w==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
