---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 128GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-data
provisioning:
  diskSelector:
    match: system_disk
  minSize: 64GiB
  grow: true
