apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - pgadmin
  - linkding

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
#   - name: homelab-configmap
#     namespace: argocd
#     literals:
#       - repoURL=https://truenas.int.1earn.ing:30008/tawdball/homelab.git

# replacements:
#   - source:
#       version: v1
#       kind: ConfigMap
#       name: homelab-configmap
#       namespace: argocd
#       fieldPath: data.repoURL
#     targets:
#       - select:
#           kind: Application
#         fieldPaths:
#         - spec.source.repoURL
#         reject:
#         - name: pgadmin

patches:
  - path: it-tools_argocd.yaml
  - path: linkding_argocd.yaml
  - path: pgadmin_argocd.yaml
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://truenas.int.1earn.ing:30008/tawdball/homelab.git
    target:
      kind: Application
      namespace: argocd
      labelSelector: isHelm=false
  - path: pgadmin_argocd.yaml
