apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  source:
    repoURL: http://truenas.local:30008/tawdball/homelab.git
    path: apps/homelab/linkding
    targetRevision: HEAD
