apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    isHelm: "true"
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    chart: home-assistant
    targetRevision: 0.3.x
    helm:
      valuesObject:
        # hostNetwork: true # Enable to use auto-discovery
        persistence:
          enabled: true

  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

