apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  destination:
    namespace: linkding
    name: in-cluster
  project: default
  source:
    path: apps/base/linkding
    repoURL: https://github.com/tawdball/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
