apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
spec:
  source:
    repoURL: https://truenas.1earn.ing:30008/tawdball/homelab.git
    targetRevision: main
    path: infra/homelab
