-- Role: authentik
-- DROP ROLE IF EXISTS authentik;

CREATE ROLE authentik WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:LzaC53j2NQtMJ0xDCSkt4g==$sUl2K4+PGi3rpDWakduVeX0ce/viXsEpLKK3Zn5iH1g=:Oaw3g9nVcSuWGH0G/bHlq46TI6tMSTqOI0x1VdcPFC0=';

COMMENT ON ROLE authentik IS 'Authentik DB User';
