-- Role: gitea
-- DROP ROLE IF EXISTS gitea;

CREATE ROLE gitea WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:HBsHwou62bIQax3PUkG9VA==$gkzbgzAsK4qJrCWErcFtcX6wCIRy/TG5lm1rYennOxk=:uCEVn5A6d5zZEeijMQAJNpqHWs/lr+4sMW9PKdWTiBE=';
