-- Role: linkding
-- DROP ROLE IF EXISTS linkding;

CREATE ROLE linkding WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:PGp56cCOzF3vQGCI+0fkeQ==$RKXjtAkwZt8QlLNIwb9YHZBauiy0sodrhngkxbchjFM=:n/nAEoRK+wUmoI5ZWAxiOgXvEXo448LYBCDmhPh6nSg=';

COMMENT ON ROLE linkding IS 'LinkDing DB user';
