-- Role: tawdball
-- DROP ROLE IF EXISTS tawdball;

CREATE ROLE tawdball WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:/uYaoOLChmaZB/aOpdyHOw==$DWdp9ELCHAZtyaTWYL8uRmwN4Dn2GHHeQmKJ6/FQ6CU=:qvqFtICnm2LTW4CbahANbF4c7bO/yv8xvGoxzV+8y1M=';
