apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  entryPoints:
  - websecure
  routes:
    # Intranet access (for now) and valid credentials required.
    # Configuration required in Authentik Proxy provider.
  - kind: Rule
    match: Host(`argocd.1earn.ing`)
    services:
    - kind: Service
      name: argocd-server
      passHostHeader: true
      port: 80
