apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingress-cert
  namespace: argocd
spec:
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  secretName: argocd-ingress-cert-secret
  dnsNames:
    - argocd.1earn.ing
    - argocd.int.1earn.ing
