apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - websecure
    - ext-websecure
  routes:
    - match: HostRegexp(`whoami\..*`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: whoami-ingress-cert-secret
