apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
spec:
  source:
    path: apps/kind/it-tools
    repoURL: http://truenas.local:30008/tawdball/homelab.git
    targetRevision: wip-gitea-only
